# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'FeedlyReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for FeedlyReader
  pod 'GoogleMLKit/Translate', '~> 3.2.0'
  pod 'SwiftSoup', '~> 2.4'
  pod 'Alamofire', '~> 5.6'
  
  target 'FeedlyReaderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OHHTTPStubs/Swift'
  end
  
  target 'FeedlyReaderUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
